services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "ericm48/postgres-demo-14.4:0.0.1"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: ${PG_DATA}
    volumes:
      - db-data:/Users/emanley/data/postgres-demo
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  db-data: